sudo: required

language: python

dist: trusty
service:
    - docker

python:
    - "2.7"

install:
   # update the docker version
   - sudo apt update -y
   - sudo apt install --only-upgrade docker-ce -y
   - docker version

   # Update docker-compose via pip
   - sudo pip install docker-compose
   - docker-compose version

   # add project requirements
   - pip install -r requirements.txt

before_script:
    - docker-compose -f docker/compose.yml up --build -d

script: python src/test.py

after_script:
    - docker-compose -f docker/compose.yml down

notifications:
    email: false

branches:
  only:
    - master
