version: '3'
services:
    web:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "5000:5000"

        networks:
            devnet:
                aliases:
                    - web
    mysql:
        build:
            context: ../
            dockerfile: docker/Dockerfile-MySQL
        ports:
            - "3306:3306"
        networks:
            devnet:
                aliases:
                    - mysql


networks:
    devnet:
