version: '3'

networks:
    devnet:

services:
    web:
        container_name: rms-web
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "5000:5000"

        networks:
            devnet:
                aliases:
                    - web
    mysql:
        container_name: rms-mysql
        build:
            context: ../
            dockerfile: docker/Dockerfile_MySQL
        ports:
            - "23306:3306"
        networks:
            devnet:
                aliases:
                    - mysql
