version: '3'
services:
    web:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "80:80"
    mysql:
        build:
            context: ../
            dockerfile: docker/Dockerfile-MySQL
        ports:
            - "3306:3306"
