version: '3'

networks:
    devnet:

services:
    web:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "5000:5000"

        networks:
            devnet:
                aliases:
                    - mysql
    mysql:
        build:
            context: ../
            dockerfile: docker/Dockerfile_MySQL
        ports:
            - "3306:3306"
        networks:
            devnet:
                aliases:
                    - mysql
