version: '3'

networks:
    devnet:

services:
    web:
        container_name: app
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ../:/code
        networks:
            devnet:
                aliases:
                    - app
    mysql:
        container_name: rms-mysql
        build:
            context: ../
            dockerfile: docker/Dockerfile_MySQL
        ports:
            - "23306:3306"
        networks:
            devnet:
                aliases:
                    - mysql
